// src/components/InfoDrawer.jsx
'use client';

import { X, ShieldCheck, FileText, Info, Mail } from 'lucide-react';

export default function InfoDrawer({ isOpen, onClose, activeTab }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-hidden bg-slate-950/60 backdrop-blur-xs animate-in fade-in duration-200">
      <div className="absolute inset-0" onClick={onClose} />

      <div className="fixed inset-y-0 right-0 max-w-full flex pl-10">
        <div className="w-screen max-w-md bg-white shadow-2xl border-l border-slate-200 flex flex-col justify-between animate-in slide-in-from-right duration-300">
          
          {/* Drawer Header */}
          <div className="p-6 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
            <div className="flex items-center gap-2.5">
              {activeTab === 'privacy' && <ShieldCheck className="w-5 h-5 text-blue-600" />}
              {activeTab === 'terms' && <FileText className="w-5 h-5 text-indigo-600" />}
              {activeTab === 'about' && <Info className="w-5 h-5 text-emerald-600" />}
              {activeTab === 'contact' && <Mail className="w-5 h-5 text-amber-600" />}

              <h2 className="text-lg font-bold text-slate-900 capitalize">
                {activeTab === 'privacy' && 'Privacy Policy'}
                {activeTab === 'terms' && 'Terms of Service'}
                {activeTab === 'about' && 'About Check Your Web'}
                {activeTab === 'contact' && 'Contact Support'}
              </h2>
            </div>

            <button
              onClick={onClose}
              className="p-1.5 rounded-xl text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Drawer Content Body */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6 text-xs sm:text-sm text-slate-600 leading-relaxed font-sans">
            
            {/* 1. PRIVACY POLICY */}
            {activeTab === 'privacy' && (
              <div className="space-y-4">
                <div>
                  <h3 className="font-bold text-slate-900 mb-1 text-sm">1. Data Collection & URL Audits</h3>
                  <p>Check Your Web is a free utility tool. We inspect only public HTML metadata and performance signals. We never store personal passwords or sensitive user credentials.</p>
                </div>
                <div>
                  <h3 className="font-bold text-slate-900 mb-1 text-sm">2. Cookies & Analytics</h3>
                  <p>We use standard session cookies to provide a smooth user experience and monitor aggregate website performance. No personal tracking data is sold to external parties.</p>
                </div>
                <div>
                  <h3 className="font-bold text-slate-900 mb-1 text-sm">3. Log Information</h3>
                  <p>Standard server access logs (browser type, requesting IP, timestamp) are retained temporarily strictly for security and rate-limiting enforcement.</p>
                </div>
              </div>
            )}

            {/* 2. TERMS OF SERVICE */}
            {activeTab === 'terms' && (
              <div className="space-y-4">
                <div>
                  <h3 className="font-bold text-slate-900 mb-1 text-sm">1. Nature of the Service</h3>
                  <p>Check Your Web provides automated simulated audits for informational and diagnostic purposes. Speed benchmarks and search visibility scores are estimates.</p>
                </div>
                <div>
                  <h3 className="font-bold text-slate-900 mb-1 text-sm">2. Disclaimer of Guarantees</h3>
                  <p>We do not guarantee specific organic rankings, revenue increases, or indexing schedules resulting from recommendations generated by this audit tool.</p>
                </div>
                <div>
                  <h3 className="font-bold text-slate-900 mb-1 text-sm">3. Fair Usage Policy</h3>
                  <p>Automated scripted flooding or distributed denial-of-service attempts against our scanning engines are strictly prohibited.</p>
                </div>
              </div>
            )}

            {/* 3. ABOUT US */}
            {activeTab === 'about' && (
              <div className="space-y-4">
                <div>
                  <h3 className="font-bold text-slate-900 mb-1 text-sm">Our Mission</h3>
                  <p>Check Your Web was built to strip away confusing technical jargon. We translate complex website health diagnostics into crystal-clear tasks that business owners and team leads can actually act upon.</p>
                </div>
                <div>
                  <h3 className="font-bold text-slate-900 mb-1 text-sm">The 7-Perspective Audit</h3>
                  <p>Instead of single-angle technical crawls, Check Your Web mirrors your site across Google SERPs, Human First-Visitors, AI Crawlers, Technical SEO, AEO, and Commercial Conversion funnels.</p>
                </div>
              </div>
            )}

            {/* 4. CONTACT US */}
            {activeTab === 'contact' && (
              <div className="space-y-4">
                <p>Have suggestions, feedback, or found an issue? Reach out directly:</p>
                <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-2">
                  <div className="text-xs text-slate-400 font-semibold uppercase">Email Inquiries</div>
                  <div className="text-sm font-bold text-blue-600 font-mono">support@checkyourweb.com</div>
                </div>
                <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-2">
                  <div className="text-xs text-slate-400 font-semibold uppercase">Response Window</div>
                  <div className="text-xs text-slate-700">We respond to technical queries within 24–48 business hours.</div>
                </div>
              </div>
            )}

          </div>

          {/* Drawer Footer */}
          <div className="p-4 border-t border-slate-100 bg-slate-50 flex items-center justify-between text-xs text-slate-400">
            <span>Check Your Web Platform</span>
            <button
              onClick={onClose}
              className="px-4 py-2 bg-slate-900 text-white rounded-xl font-semibold hover:bg-slate-800 transition-colors cursor-pointer"
            >
              Close
            </button>
          </div>

        </div>
      </div>
    </div>
  );
}